---
# tasks file for ufw

- name: Set ufw IPv6
  become: yes
  lineinfile:
    dest: /etc/default/ufw
    regexp: '^IPV6='
    line: "IPV6={{ ufw_ipv6 }}"
    state: present
  notify:
    - reload ufw
  tags:
    - ufw

- name: Set ufw logging
  become: yes
  ufw:
    logging: "{{ ufw_logging }}"
  tags:
    - ufw

- name: Set incoming policy
  become: yes
  ufw:
    policy: "{{ ufw_incoming_policy }}"
    direction: incoming
  tags:
    - ufw

- name: Set ougoing policy
  become: yes
  ufw:
    policy: "{{ ufw_outgoing_policy }}"
    direction: outgoing
  tags:
    - ufw

- name: Set routed policy
  become: yes
  ufw:
    policy: "{{ ufw_routed_policy }}"
    direction: routed
  tags:
    - ufw

- name: Configure ufw rules
  become: yes
  ufw:
    rule: "{{ item.rule|default('allow') }}"
    proto: "{{ item.proto|default(omit) }}"
    src: "{{ item.src|default(omit) }}"
    to_port: "{{ item.to_port|default(omit) }}"
  with_items:
    - "{{ ufw_rules }}"
  tags:
    - ufw

- name: Enable ufw
  become: yes
  ufw:
    state: enabled
  tags:
    - ufw
