---
# tasks file for ufw (Ubuntu specific)

- name: Install ufw packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ ufw_packages }}"
  tags:
    - ufw
